load("@rules_layer_optimizer//layers:defs.bzl", "layer_group")
load("@rules_layer_optimizer//layers:distroless.bzl", "optimized_layers")
load("@rules_layer_optimizer//python:inference.bzl", "env_file", "env_inference")
load("@rules_layer_optimizer//python:rules_python.bzl", "py_image_layer")
load("@rules_python//python:py_binary.bzl", "py_binary")
load(":runtime_test.bzl", "runtime_test")

py_binary(
    name = "app",
    srcs = ["app.py"],
    legacy_create_init = False,
    deps = [
        "@pip//colorama",
        "@pip//python_dateutil",
    ],
)

py_image_layer(
    name = "layers",
    binary = ":app",
    strip_prefix = "app",
)

optimized_layers(
    name = "archive",
    compress = "gzip",
    flatten_all = True,
    groups = [
        layer_group(
            name = "interpreter",
            targets = [":layers_interpreter"],
        ),
        layer_group(
            name = "pip",
            overflow = "flatten",
            targets = [":layers_pip"],
        ),
        layer_group(
            name = "source",
            targets = [":layers_source"],
        ),
    ],
    layer_budget = 1,
    size_bytes_threshold = 1,
)

env_inference(
    name = "colorama",
    env = {"COLORAMA_AVAILABLE": "1"},
    for_deps = [
        "@pip//colorama",
        "@pip//python_dateutil",
    ],
)

env_file(
    name = "env",
    base_env = {},
    extra_env = {},
    inferences = [":colorama"],
    runfiles_root = "/app.runfiles",
    deps = [":app"],
)

runtime_test(
    name = "runtime_test",
    archive = ":archive",
    env = ":env",
    packages = ":layers_pip",
)
