"""Helpers that turn `uv.lock` into pip package size hints.

The OCI image layer optimizer needs package sizes during Bazel analysis, not
during execution. `pip_size_hints_repository` reads the lock while generating
the analysis-time size-hint file.
"""

load("@toml.bzl//:toml.bzl", "toml")

def parse_uv_lock_size_hints(lock_content, size_overrides = {}):
    """Returns exact wheel sizes and caller-provided package fallbacks.

    This is public for Starlark unit tests so tests cover the same parsing path
    used by the repository rule.

    Args:
        lock_content: String contents of a `uv.lock` TOML file.
        size_overrides: Fallback compressed sizes keyed by normalized distribution name.

    Returns:
        A struct containing wheel_sizes, package_sizes, and package_overrides.
    """
    lock_data = toml.decode(lock_content)
    wheel_sizes = {}
    package_sizes = {}
    packages = {}
    packages_allowing_overrides = {}

    for package in lock_data.get("package", []):
        package_name = package.get("name")
        if not package_name:
            continue

        normalized_package = _normalize_package(package_name)
        packages[normalized_package] = True
        wheels = package.get("wheels", [])
        if not wheels or package.get("sdist") != None:
            packages_allowing_overrides[normalized_package] = True
        for wheel in wheels:
            filename = wheel.get("url", "").rsplit("/", 1)[-1]
            size = wheel.get("size")
            if size == None:
                packages_allowing_overrides[normalized_package] = True
            if not filename or size == None:
                continue
            previous_size = wheel_sizes.get(filename)
            if previous_size != None and previous_size != size:
                fail("wheel {} has conflicting sizes {} and {}".format(filename, previous_size, size))
            wheel_sizes[filename] = size
            package_sizes[normalized_package] = max(package_sizes.get(normalized_package, 0), size)

    package_overrides = {}
    for package, raw_size in size_overrides.items():
        normalized_package = _normalize_package(package)
        if normalized_package not in packages:
            fail("pip size override refers to package not present in the lock: {}".format(package))
        if normalized_package not in packages_allowing_overrides:
            fail("pip size override for {} requires an sdist or an unsized wheel".format(package))
        size = int(raw_size)
        if size <= 0:
            fail("pip size override for {} must be positive, got {}".format(package, raw_size))
        package_overrides[normalized_package] = size
        package_sizes[normalized_package] = size

    return struct(
        package_overrides = package_overrides,
        package_sizes = package_sizes,
        wheel_sizes = wheel_sizes,
    )

def parse_pip_size_overrides(size_overrides):
    """Create size hints without requiring a uv lockfile.

    Args:
        size_overrides: Distribution names mapped to positive size strings.

    Returns:
        Size metadata with package estimates and no exact wheel sizes.
    """
    sizes = {}
    for package, raw_size in size_overrides.items():
        normalized = _normalize_package(package)
        size = int(raw_size)
        if size <= 0:
            fail("pip size override for {} must be positive, got {}".format(package, raw_size))
        if normalized in sizes and sizes[normalized] != size:
            fail("conflicting pip size overrides for " + normalized)
        sizes[normalized] = size
    return struct(package_overrides = sizes, package_sizes = sizes, wheel_sizes = {})

def render_pip_size_hint_bzl(size_hints):
    """Renders the generated `pip_pkg_size_hint.bzl` file content.

    This is public for Starlark unit tests so tests cover the same deterministic
    rendering path used by the repository rule.

    Args:
        size_hints: Size-hint struct returned by `parse_uv_lock_size_hints`.

    Returns:
        String containing the complete Starlark source for `pip_pkg_size_hint.bzl`,
        including the `PIP_PACKAGE_SIZE_HINTS` dict definition.
    """
    lines = [
        '"""',
        "Generated pip package size hints derived from uv.lock.",
        "",
        "Generated by the OCI image inference module extension. Do not edit it",
        "directly; update the configured uv.lock instead and rerun Bazel.",
        '"""',
        "",
        "PIP_WHEEL_SIZE_HINTS = {",
    ]

    for wheel in sorted(size_hints.wheel_sizes.keys()):
        lines.append('    "{}": {},'.format(wheel, size_hints.wheel_sizes[wheel]))

    lines.extend([
        "}",
        "",
        "PIP_PACKAGE_SIZE_OVERRIDES = {",
    ])
    for package in sorted(size_hints.package_overrides.keys()):
        lines.append('    "{}": {},'.format(package, size_hints.package_overrides[package]))

    lines.extend([
        "}",
        "",
        "PIP_PACKAGE_SIZE_HINTS = {",
    ])
    for package in sorted(size_hints.package_sizes.keys()):
        lines.append('    "{}": {},'.format(package, size_hints.package_sizes[package]))

    lines.append("}")
    return "\n".join(lines) + "\n"

def _pip_size_hints_repository_impl(rctx):
    if rctx.attr.lock:
        size_hints = parse_uv_lock_size_hints(rctx.read(rctx.attr.lock), rctx.attr.size_overrides)
    else:
        size_hints = parse_pip_size_overrides(rctx.attr.size_overrides)
    rctx.file("BUILD.bazel", "exports_files([\"size_hints.bzl\"])\n")
    rctx.file("size_hints.bzl", render_pip_size_hint_bzl(size_hints))

pip_size_hints_repository = repository_rule(
    implementation = _pip_size_hints_repository_impl,
    attrs = {
        "lock": attr.label(allow_single_file = [".lock"]),
        "size_overrides": attr.string_dict(),
    },
)

def _normalize_package(package):
    normalized = []
    for char in package.lower().elems():
        if char in "-_.":
            if not normalized or normalized[-1] != "_":
                normalized.append("_")
        else:
            normalized.append(char)
    return "".join(normalized)
