"""Helpers for matching canonical external-repository paths."""

_REPOSITORY_SEPARATOR_PATTERN = "[+~]"

def module_extension_repo_pattern(module, extension, repository_prefix = ""):
    """Return a path regex for a repository generated by a module extension."""
    separator = _REPOSITORY_SEPARATOR_PATTERN
    return "{}{}{}{}{}{}".format(
        module,
        separator,
        separator,
        extension,
        separator,
        repository_prefix,
    )

def repository_rule_repo_pattern(rule_name):
    """Return a path regex for a repository generated by a repository rule."""
    separator = _REPOSITORY_SEPARATOR_PATTERN
    return "{}{}{}".format(separator, rule_name, separator)

def repository_rule_repo_in_path(path, rule_name):
    """Return whether a path contains a canonical repository-rule segment."""
    return "+{}+".format(rule_name) in path or "~{}~".format(rule_name) in path
