"""Helpers for matching canonical external-repository paths."""

_REPOSITORY_SEPARATOR_PATTERN = "[+~]"

def module_extension_repo_pattern(module, extension, repository_prefix = ""):
    """Return a path regex for a repository generated by a module extension."""
    separator = _REPOSITORY_SEPARATOR_PATTERN
    return "{}{}{}{}{}{}".format(
        module,
        separator,
        separator,
        extension,
        separator,
        repository_prefix,
    )
