module(name = "rules_layer_optimizer_examples")

bazel_dep(name = "rules_layer_optimizer", version = "0.0.0")
local_path_override(
    module_name = "rules_layer_optimizer",
    path = "..",
)

bazel_dep(name = "aspect_rules_py", version = "2.0.0-alpha.4")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "rules_shell", version = "0.6.1")

python = use_extension("@aspect_rules_py//py:extensions.bzl", "python_interpreters")
python.toolchain(python_version = "3.12")
use_repo(python, "python_3_12_x86_64_unknown_linux_gnu", "python_interpreters")

register_toolchains("@python_interpreters//:all")

uv = use_extension("@aspect_rules_py//uv:extensions.bzl", "uv")
uv.declare_hub(hub_name = "packages")
uv.project(
    hub_name = "packages",
    lock = "//:uv.lock",
    pyproject = "//:pyproject.toml",
)
use_repo(uv, "packages")

inference = use_extension("@rules_layer_optimizer//inference:extensions.bzl", "oci_image_inference")
inference.configure(
    dependency_attributes = [
        "deps",
        "src",
        "srcs",
        "actual",
        "venv",
    ],
    pip_hub = "@packages//:defs.bzl",
)
inference.pip_size_hint(lock = "//:uv.lock")
use_repo(inference, "oci_image_inference_config")

bazel_dep(name = "rules_python", version = "1.9.0")

rules_python = use_extension("@rules_python//python/extensions:python.bzl", "python")
rules_python.defaults(python_version = "3.12")
rules_python.toolchain(python_version = "3.12")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "ubuntu",
    digest = "sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3",
    image = "docker.io/library/ubuntu",
    platforms = ["linux/amd64"],
)
use_repo(oci, "ubuntu", "ubuntu_linux_amd64")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pip",
    python_version = "3.12",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pip")

bazel_dep(name = "rules_img", version = "0.3.22")

images = use_extension("@rules_img//img:extensions.bzl", "images")
images.pull(
    name = "img_ubuntu",
    digest = "sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3",
    layer_handling = "eager",
    registry = "index.docker.io",
    repository = "library/ubuntu",
)
use_repo(images, "rules_img_images.bzl")
