load("@rules_layer_optimizer//python:rules_python.bzl", "pip_layer_reducer", "py_image_layer")
load("@rules_python//python:py_binary.bzl", "py_binary")
load(":sharing_test.bzl", "sharing_test")

_DEPS = [
    "@pip//backports_strenum",
    "@pip//backports_tarfile",
    "@pip//colorama",
    "@pip//google_crc32c",
]

py_binary(
    name = "app",
    srcs = ["app.py"],
    legacy_create_init = False,
    deps = _DEPS,
)

py_binary(
    name = "other",
    srcs = ["app.py"],
    legacy_create_init = False,
    main = "app.py",
    deps = _DEPS,
)

py_image_layer(
    name = "app_layers",
    binary = ":app",
    strip_prefix = "reuse/app",
)

pip_layer_reducer(
    name = "other_layers",
    deps = [":other"],
)

sharing_test(
    name = "sharing_test",
    expected_count = 4,
    other = ":other_layers",
    target_under_test = ":app_layers_pip",
)
