module(name = "rules_python_layers")

bazel_dep(name = "rules_layer_optimizer")
local_path_override(
    module_name = "rules_layer_optimizer",
    path = "../..",
)

bazel_dep(name = "aspect_bazel_lib", version = "2.22.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_python", version = "1.9.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = "3.12")
python.toolchain(python_version = "3.12")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    enable_implicit_namespace_pkgs = True,
    hub_name = "pip",
    python_version = "3.12",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pip")

inference = use_extension("@rules_layer_optimizer//inference:extensions.bzl", "oci_image_inference")
inference.configure(
    dependency_attributes = [
        "deps",
        "src",
        "srcs",
        "actual",
        "venv",
    ],
    pip_hub = "@pip//:requirements.bzl",
)
inference.pip_size_hint(lock = "//:uv.lock")
use_repo(inference, "oci_image_inference_config")
