"""Tests for pip size hint repository rendering helpers."""

load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load(
    "//python/private:pip_size_hints_repository.bzl",
    "parse_pip_size_overrides",
    "parse_uv_lock_size_hints",
    "render_pip_size_hint_bzl",
)

def _parse_uv_lock_test_impl(ctx):
    """Validate the uv.lock parsing behavior used by the repository rule."""
    env = unittest.begin(ctx)
    explicit = parse_pip_size_overrides({"A...Pkg--Name": "101"})
    asserts.equals(env, struct(
        package_sizes = {"a_pkg_name": 101},
        package_overrides = {"a_pkg_name": 101},
        wheel_sizes = {},
    ), explicit)

    size_hints = parse_uv_lock_size_hints("""
[[package]]
name = "A...Pkg--Name"
wheels = [{ url = "https://example.invalid/a_pkg_name-1-py3-none-any.whl", size = 100 }]

[[package]]
name = "sdist-only"

[[package]]
name = "multi-wheel"
wheels = [
  { url = "https://example.invalid/multi_wheel-1-manylinux_aarch64.whl", size = 200 },
  { url = "https://example.invalid/multi_wheel-1-manylinux_x86_64.whl", size = 300 },
]

[[package]]
name = "sdist-with-sized-wheel"
sdist = { url = "https://example.invalid/sdist_with_sized_wheel-1.tar.gz", size = 80 }
wheels = [{ url = "https://example.invalid/sdist_with_sized_wheel-1-manylinux_x86_64.whl", size = 90 }]

[[package]]
name = "torch"
wheels = [{ url = "https://example.invalid/torch.whl" }]
	""", {
        "sdist-with-sized-wheel": "120",
        "torch": "175833687",
    })

    asserts.equals(env, struct(
        package_overrides = {"sdist_with_sized_wheel": 120, "torch": 175833687},
        package_sizes = {"a_pkg_name": 100, "multi_wheel": 300, "sdist_with_sized_wheel": 120, "torch": 175833687},
        wheel_sizes = {
            "a_pkg_name-1-py3-none-any.whl": 100,
            "multi_wheel-1-manylinux_aarch64.whl": 200,
            "multi_wheel-1-manylinux_x86_64.whl": 300,
            "sdist_with_sized_wheel-1-manylinux_x86_64.whl": 90,
        },
    ), size_hints)

    return unittest.end(env)

parse_uv_lock_test = unittest.make(_parse_uv_lock_test_impl)

def _wheel_sizes_test_impl(ctx):
    """Every wheel retains its own size so analysis can select the configured one."""
    env = unittest.begin(ctx)

    size_hints = parse_uv_lock_size_hints("""
[[package]]
name = "leading-macos"
wheels = [
  { url = "https://x.invalid/leading_macos-1-cp312-macosx_13_0_arm64.whl", size = 11 },
  { url = "https://x.invalid/leading_macos-1-cp312-manylinux_2_17_x86_64.whl", size = 22 },
]

[[package]]
name = "aarch64-is-not-x86"
wheels = [
  { url = "https://x.invalid/a-1-cp312-manylinux_2_17_aarch64.whl", size = 33 },
  { url = "https://x.invalid/a-1-cp312-manylinux_2_17_x86_64.whl", size = 44 },
]

[[package]]
name = "pure-python"
wheels = [
  { url = "https://x.invalid/pure_python-1-py3-none-macosx_11_0_arm64.whl", size = 55 },
  { url = "https://x.invalid/pure_python-1-py3-none-any.whl", size = 66 },
]

[[package]]
name = "no-linux-build"
wheels = [
  { url = "https://x.invalid/no_linux_build-1-cp312-macosx_13_0_arm64.whl", size = 77 },
  { url = "https://x.invalid/no_linux_build-1-cp312-win_amd64.whl", size = 88 },
]
    """)

    asserts.equals(env, struct(
        package_overrides = {},
        package_sizes = {"leading_macos": 22, "aarch64_is_not_x86": 44, "pure_python": 66, "no_linux_build": 88},
        wheel_sizes = {
            "leading_macos-1-cp312-macosx_13_0_arm64.whl": 11,
            "leading_macos-1-cp312-manylinux_2_17_x86_64.whl": 22,
            "a-1-cp312-manylinux_2_17_aarch64.whl": 33,
            "a-1-cp312-manylinux_2_17_x86_64.whl": 44,
            "pure_python-1-py3-none-macosx_11_0_arm64.whl": 55,
            "pure_python-1-py3-none-any.whl": 66,
            "no_linux_build-1-cp312-macosx_13_0_arm64.whl": 77,
            "no_linux_build-1-cp312-win_amd64.whl": 88,
        },
    ), size_hints)

    return unittest.end(env)

wheel_sizes_test = unittest.make(_wheel_sizes_test_impl)

def _render_size_hint_bzl_test_impl(ctx):
    """Validate deterministic generated Starlark output for debugging diffs."""
    env = unittest.begin(ctx)

    rendered = render_pip_size_hint_bzl(struct(
        package_overrides = {"b_pkg": 3},
        package_sizes = {"a_pkg": 1, "b_pkg": 3},
        wheel_sizes = {"b.whl": 2, "a.whl": 1},
    ))

    expected = '''"""
Generated pip package size hints derived from uv.lock.

Generated by the OCI image inference module extension. Do not edit it
directly; update the configured uv.lock instead and rerun Bazel.
"""

PIP_WHEEL_SIZE_HINTS = {
    "a.whl": 1,
    "b.whl": 2,
}

PIP_PACKAGE_SIZE_OVERRIDES = {
    "b_pkg": 3,
}

PIP_PACKAGE_SIZE_HINTS = {
    "a_pkg": 1,
    "b_pkg": 3,
}
'''
    asserts.equals(env, expected, rendered)

    return unittest.end(env)

render_size_hint_bzl_test = unittest.make(_render_size_hint_bzl_test_impl)

def pip_size_hints_repository_test_suite(name):
    """Call the pip size hints repository helper test suite.

    Args:
        name: Name of the generated target or test suite.
    """
    parse_uv_lock_test(
        name = name + "_parse_uv_lock_test",
    )

    render_size_hint_bzl_test(
        name = name + "_render_size_hint_bzl_test",
    )

    wheel_sizes_test(
        name = name + "_wheel_sizes_test",
    )

    native.test_suite(
        name = name,
        tests = [
            ":" + name + "_parse_uv_lock_test",
            ":" + name + "_render_size_hint_bzl_test",
            ":" + name + "_wheel_sizes_test",
        ],
    )
